version: '3.8'

services:
  service_1:
    build:
      context: .
      dockerfile: Dockerfile.service_1
    ports:
      - 8000:80
    volumes:
      - ./service_1:/var/www/html

  service_2:
    build:
      context: .
      dockerfile: Dockerfile.service_2
    ports:
      - 80:80
    volumes:
      - ./service_2:/var/www/html

  service_3:
    build:
      context: .
      dockerfile: Dockerfile.service_3
    ports:
      - 88:80
    volumes:
      - ./service_3:/var/www/html
